chore: add step to check index.html

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -32,11 +32,18 @@ jobs:
           npm install -g @lhci/cli@0.14.x
           npm install -g http-server
 
+      - name: Check if index.html exists
+        run: |
+          if [ ! -f public/index.html ]; then
+            echo "index.html not found"
+            exit 1
+          fi
+
       - name: Discord Notify (index.html not found)
         if: failure()
         run: |
           curl -X POST -H "Content-Type: application/json" \
-            -d "{\"content\": \"🚨 \`index.html\` 파일이 없습니다. Lighthouse 워크플로우를 중단했습니다.\\n📁 repository: ${{ github.repository }}\\n👤 triggerd by: ${{ github.actor }}\"}" \
+            -d "{\"content\": \"🚨 \`index.html\` 파일이 없습니다. 워크플로우를 중단했습니다.\\n📁 repository: ${{ github.repository }}\\n👤 triggered by: ${{ github.actor }}\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
 
       - name: Start local server
